config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  resources :users

end

app/models/avatar.rb
class Avatar < ActiveRecord::Base
	belongs_to :user_avatar

	has_attached_file :avatar, styles: { medium: "180x180>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	#validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
	validates :avatar, attachment_presence: true
	validates :avatar, attachment_size: { less_than: 1.megabytes }
	validates :avatar, attachment_content_type: { content_type: ['image/png','image/jpeg'] }
	#validates :avatar, attachment_content_type: { content_type: 'application/vnd.oasis.opendocument.text' }
	#validates :avatar, attachment_content_type: { content_type: 'application/msword' }
end

app/models/user.rb
class User < ActiveRecord::Base
	enum kind: { 'текст'=>'text', 'картинка'=>'picture', 'звук'=>'audio', 'видео'=>'video' }

	validates :name, presence: true

	validates :kind, { presence:true }

	has_attached_file(
		:avatar,
		styles: {
			medium: "120x120>",
			thumb: "32x32>"
		},
		:storage => :s3,
		:s3_region => ENV['AWS_REGION'],
		:bucket => 'uploader-54724724rg', 
		:s3_credentials => {
			:access_key_id => ENV['AWS_ACCESS_KEY'], 
			:secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
		}
	)

	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/models/user_avatar.rb
class UserAvatar < ActiveRecord::Base
	belongs_to :user
	has_one :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :debug_info

	def index
		@list = User.all
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		
		puts "===== UsersController#create ====="
		puts @user.avatar
		puts "===== UsersController#create ====="
		
		begin
			@user.save!
			redirect_to users_path
		rescue
			render :new
		end
	end

	def show
		@user = User.find_by(id: params[:id])
	end

	def edit
		@user = User.find_by(id: params[:id])
	end

	def update
		puts "===== Users#update, params: =====> #{params}"
		@user = User.find_by(id: params[:id])
		#@user.avatar = nil if not params[:user][:avatar].nil?
		if @user.update_attributes(user_params)
			redirect_to user_path(@user)
		else
			render :edit
		end
	end

	def destroy
		@user = User.find_by(id: params[:id])
		@user.destroy!
		redirect_to users_path
	end


	private
		def user_params
			params.require(:user).permit(
				:name, 
				:email, 
				:avatar, 
				:kind,
			)
		end
		
		def debug_info
			puts ''
			puts "========== debug_info starts =========="
			ap params
			#~ if !params[:user].nil?
				#~ puts params[:user][:avatar].content_type if params[:user].has_key?(:avatar)
			#~ end
			puts "========== debug_info ends =========="
			puts ''
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Uploader</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_errors.html.erb
<% if object.errors.any? %>

	<div id="error_explanation">
		<div class="alert alert-danger">
			Форма содержит ошибки:
		</div>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>

<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
	<%=  render 'errors', object: f.object %>
	
	<%= select_tag 'user[kind]', options_for_select(User.kinds, 'picture') %>

	<%= f.label :name, 'Имя' %>
	<%= f.text_field :name %><br><br>

	<%= f.label :email, 'Почта' %>
	<%= f.text_field :email %><br><br>
	
	<%= f.label :avatar, 'Лик' %>
	<%= f.file_field :avatar %><br><br>

	<%= f.submit %>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>

<%= render 'form' %>

<p>
	<%= link_to 'К списку', users_path %>
</p>

app/views/users/index.html.erb
<h1>Users#index</h1>

<hr>
<span class="glyphicon glyphicon-search"></span>
<hr>

<ul>
	<% @list.each do |u| %>
		<li>
			
			<%= link_to user_path(u) do %>
				<%= image_tag u.avatar.url(:thumb) %>
				<%= "#{u.name} (#{u.kind})" %>
			<% end %>
			<%= link_to '(и)', edit_user_path(u), title:'Изменить' %> 
			<%= link_to '(x)', user_path(u), method: :delete, title:'Удалить', data: { confirm: "Удалить пользователя '#{u.name}'?" } %>
		</li>
	<% end %>
</ul>
<hr>
<%= link_to 'Создать', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= render 'form' %>

<p>
	<%= link_to 'К списку', users_path %>
</p>

app/views/users/show.html.erb
<h1>Users#show</h1>

<table width="50%" align="center" border="3" cols="3">
	<tr><!-- тип, аватар -->
		<td>Тип:</td>
		<td><%= @user.kind %></td>
		<td rowspan="3" align="center" valign="center">
			<%= link_to @user.avatar.url do %>
				<%= image_tag @user.avatar.url(:medium) %>
			<% end %>
		</td>
	</tr>
	<tr><!-- имя -->
		<td>Имя: </td>
		<td><%= @user.name  %></td>
	</tr>
	<tr><!-- почта -->
		<td>Почта: </td>
		<td><%= @user.email  %></td>
	</tr>
	<tr><!-- кнопки -->
		<td>
			<%= link_to users_path do %>
				<button>Список</button>
			<% end %>
		</td>
		<td>
			<%= link_to edit_user_path(@user) do %>
				<button>Изменить</button>
			<% end %>
		</td>
		<td>
			<%= link_to user_path(@user), method: :delete, data: { confirm: 'Удалить?' } do %>
				<button>Удалить</button>
			<% end %>
		</td>
	</tr>
</table>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>